project_id = "cknlxuespsymlvtwkeqh"

[functions.verify-business]
verify_jwt = false

[functions.verify-business-batch]
verify_jwt = false

[functions.verify-pi-token]
verify_jwt = false

[functions.approve-pi-payment]
verify_jwt = false

[functions.complete-pi-payment]
verify_jwt = false

[functions.get-subscription-status]
verify_jwt = false

[functions.get-payment-history]
verify_jwt = false
